site_name: 'The Ultimate Internet Bookmark: A Collection of Must-Visit Links'
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 
    scheme: slate
    primary: black
    accent: indigo
  features:
    - header.autohide
    - navigation.expand
    - navigation.tabs
plugins:
  - search:
      
nav:
  - Home: index.md
  - Life:
    - Dunia: life_dunia.md
    - Hati: life_hati.md
    - Quran: life_quran.md
    - Keluarga: life_keluarga.md
    # - Tauhid: life_tauhid.md
  # - Gaming:
    # - Semarang: semarang.md
    # - Semarang: semarang.md
  # - App:
    # - Semarang: semarang.md
    # - Semarang: semarang.md
  # - Knowledge:
    # - Pajak: pajak.md
    # - Coding: semarang.md
    # - Excel: excel.md